feat(coral-tokens): adding coral tokens package
divetool/coral pull request #11
Opened 2022-11-05 21:56 UTC by AndresVD21

## Current Behavior

No package to handle the tokens generation

## Expected Behavior

Have the project for the design system tokens created and the transformation to generate color shades based on primary, secondary and tertiary colors (preliminary colors).

## Related Issue(s)

Fixes #

# Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] Added new tests to cover the fix / functionality

2022-11-06 00:49 UTC, sebastiandg7 commented
@AndresVD21 we need to ignore the stencil generate `components.ts` file from the `@divetool/coral-angular` lint target.

2022-11-06 23:47 UTC, sebastiandg7 requested changes

2022-11-06 23:47 UTC, sebastiandg7 commented on package.json
> +    "@divetool/coral": "^0.0.5",
Please remove this package from the workspace package.json

2022-11-07 00:25 UTC, AndresVD21 commented on package.json
> +    "@divetool/coral": "^0.0.5",
Done!

2022-11-07 02:35 UTC, sebastiandg7 approved these changes

2022-11-07 02:49 UTC, merged